language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install cython
  - pip install numpy
  - pip install scikit-learn # needed for benchmark
  - pip install .
# command to run tests
script: 
  - python setup.py test
  - time python benchmark.py 500
